slides:
	pandoc -s -o example.html -t revealjs --template=template.html -V revealjs-url="../../../util/reveal.js/3.3.0" --slide-level=2 --mathjax example.md

tex:
	pandoc -o example.tex example.md

pdf:
	pandoc -o example.pdf example.md

docx:
	pandoc -o example.docx example.md

html:
	pandoc -s -o example.html --mathjax example.md 

